// AUTO-GENERATED by scripts/generate-builtins.mjs. Do not edit.

import '../character/character-sync.js';
import './chat-host.js';
import './party-host.js';
import './world-positions-host.js';
import '../session/participants-sync.js';
