// AUTO-GENERATED by scripts/generate-builtins.mjs. Do not edit.

import '../character/character-sync.js';
import './chat-host.js';
import '../chat/chat-control.js';
import './party-host.js';
import './world-positions-host.js';
import '../session/participants-sync.js';
import '../world/world-control.js';
import '../world/travel-session.js';
import '../world/travel-control.js';
import '../interactions/interactions-session.js';
import '../interactions/interactions-control.js';
