const MAP_LUMENFORD = {
    id: 'LUMENFORD',
    name: '등불도시 루멘포드',
    description: '성유와 등불의 도시. 폭풍 전선을 막아내는 격자와 검은 수로 위에 지어진 난민 수도. 상업과 비밀, 의식과 과학이 얽혀 있다.',
    entryFieldId: 'gate',
    prev: null,
    next: 'BACKSTREETS',
    theme: {
        tag: 'dark-cyber-worn-teal',
        mood: 'tense-hopeful',
    },
    bg: {
        path: '/assets/bg/maps/lumenford/city_gate.webp',
        position: 'center 70%',
        focalPoint: 'city-gate-lantern',
        parallax: 0.1,
        overlay: 'grain',
        grade: 'cool',
        description: '야간, 젖은 현무암 도로 위로 청록빛 네온과 주황색 등불이 길게 번진다. ' +
            '우측엔 격자 탑이 청백색 아크 라인을 뽑고, 중앙 포커스는 성문 랜턴의 난반사. ' +
            '비막 구름이 낮게 깔려 있으며 원근으로 난민 행렬의 실루엣이 끊기지 않게 이어진다. ' +
            '질감은 금속/석재가 뚜렷하고, 색의 대비는 차갑고 낮으며, 공기엔 희미한 입자감(그레인).',
        gifRecommended: true,
        llmPrompt: 'Dark cyber worn‑teal city gate at night; wet basalt road with teal neon reflections and amber lanterns; ' +
            'a lattice tower emits pale arc lines; low cloud ceiling; continuous refugee silhouettes; high material detail; cool grade; subtle grain; loopable parallax fog.',
    },
    music: {
        mood: 'ambient-industrial + muted choirs',
        tracks: [
            '/assets/audio/maps/lumenford/ambient.ogg',
            '/assets/audio/maps/lumenford/ambient.mp3',
            '/assets/audio/maps/shared/wind_low.ogg',
        ],
        loop: true,
        volume: 0.7,
        cuePoints: [
            { name: 'intro', time: 0 },
            { name: 'loop', time: 18.0 },
        ],
        description: '템포 느림(55~65BPM), 저역 서브 드론과 얇은 톤의 합창 패드. 틴/철제 잔향, 비 소리의 고역 쉼표. ' +
            '디스토션은 미세하게, 스테레오 폭 좁음→중간으로 서서히 확장. 청록 네온/등불 대비를 느끼게 하는 차분한 긴장.',
        llmPrompt: 'Slow ambient industrial with distant muted choir; low sub drone, thin glassy pad; subtle metallic reverb; light rain hiss; minimal distortion; narrow→medium stereo swell; tense but hopeful.',
    },
    fields: [
        {
            id: 'gate',
            name: '성문(Entry)',
            kind: 'entry',
            description: '통행세와 통행증 검문이 이뤄지는 북문. 등불탑이 도시를 비춘다.',
            neighbors: ['market', 'docks'],
            bg: {
                path: '/assets/bg/maps/lumenford/gate_close.webp',
                position: 'center bottom',
                focalPoint: 'lantern-tower',
                overlay: 'grain',
                grade: 'cool',
                description: '클로즈업: 랜턴 기둥 하부, 금속 그릴에 떨어지는 비와 응축수. ' +
                    '검문소 간판의 청록 네온이 깜빡이며 표면에 길게 반사. 인파는 허리 위 실루엣만, 흐림 심도 얕음.',
                gifRecommended: true,
                llmPrompt: 'Close shot of lantern tower base with rain beads, teal neon flicker reflecting on metal grilles; shallow depth of field; loopable subtle flicker.',
            },
            musicCue: {
                mood: 'brass low + gate bustle',
                tracks: ['/assets/audio/maps/lumenford/gate.ogg'],
                loop: true,
                volume: 0.8,
                description: '저음 브라스 드론, 멀리서 웅성거림·발소리·장비 금속 마찰 샘플을 레이어. ' +
                    '템포 프리, 간헐적 신호음(짧은 네온 플리커 샘플)로 포인트.',
                llmPrompt: 'Low brass drone + crowd/footstep/metal scrapes ambience; free tempo; occasional short neon flicker tone; understated mix.',
            },
        },
        {
            id: 'market',
            name: '상점가',
            kind: 'market',
            description: '부두길드 상인과 밀수꾼이 섞여드는 시장. 정보와 장비가 교차한다.',
            neighbors: ['gate', 'archives'],
            bg: {
                path: '/assets/bg/maps/lumenford/market.webp',
                position: 'center 65%',
                overlay: 'grain',
                grade: 'cool',
                description: '좁은 골목형 상점가, 여러 색 온도의 네온 간판이 젖은 포장도로에 다중 반사. ' +
                    '매연과 증기가 천천히 흘러가며 원근 빛이 퍼진다. 현수막과 전선이 프레임을 가로지르며 텍스처 감 강조.',
                gifRecommended: true,
                llmPrompt: 'Worn teal cyberpunk market alley; mixed neon signage reflecting on wet pavement; slow steam plumes; hanging banners and cables crossing the frame; loopable steam motion.',
            },
            musicCue: {
                mood: 'rhythmic stalls + low pads',
                tracks: ['/assets/audio/maps/lumenford/market.ogg'],
                loop: true,
                volume: 0.7,
                description: '로우파이 리듬(경쾌 X), 목재 박자 샘플과 소프트 신스 베이스. ' +
                    '상점 종소리/지폐·금속 소품의 미세한 폴리사운드를 사이드체인 없이 얕게 믹스.',
                llmPrompt: 'Lo-fi market rhythm with wooden percussive ticks, soft synth bass, faint shop bells and coin/metal foley, no heavy sidechain; moderate space.',
            },
        },
        {
            id: 'archives',
            name: '학술 아케이브',
            kind: 'interior',
            description: '유적도서관 분소. 봉인된 열람실로 가는 허가증이 필요한 곳.',
            neighbors: ['market'],
            bg: {
                path: '/assets/bg/maps/lumenford/archives.webp',
                position: 'center 45%',
                overlay: 'fog',
                grade: 'cool',
                description: '유리 진공 케이스 속 청록빛 공허수정 샘플이 내부에서 은은히 발광. ' +
                    '차가운 주광(6500K) 스폿, 라벨과 유물 표면에 가는 먼지 입자. 반사/굴절 표현 강조.',
                llmPrompt: 'Museum-like archive interior with teal-glowing void shard in vacuum glass case; cool spotlights; dust motes; emphasize reflection/refraction details.',
            },
            musicCue: {
                mood: 'glass harmonics + hush',
                tracks: ['/assets/audio/maps/lumenford/archives.ogg'],
                loop: true,
                volume: 0.6,
            },
        },
        {
            id: 'docks',
            name: '부두',
            kind: 'docks',
            description: '검은 수로 위 격납 링. 프리 컴퍼니의 이착륙 포인트.',
            neighbors: ['gate'],
            bg: {
                path: '/assets/bg/maps/lumenford/docks.webp',
                position: 'center bottom',
                overlay: 'fog',
                grade: 'cool',
                description: '짙은 안개 위에 부표와 항로 표식 조명 라인이 리듬감 있게 연속. ' +
                    '수면은 느린 장력파가 번지고, 격납고 조명은 간헐적으로 깜빡인다.',
                gifRecommended: true,
                llmPrompt: 'Foggy docks with buoy beacons and runway-like light lines; slow water ripples; occasional hangar light flicker; loopable subtle motion.',
            },
            musicCue: {
                mood: 'low wind + distant horns',
                tracks: ['/assets/audio/maps/shared/wind_low.ogg'],
                loop: true,
                volume: 0.65,
                description: '저음 바람/해무 앰비언스, 멀리서 짧은 혼 경적이 드물게 울림. 잔향 길고 공간감 넓음.',
                llmPrompt: 'Low wind/sea mist ambience; rare distant short foghorn calls; long tail reverb; wide spatial field.',
            },
        },
    ],
};
const MAP_BACKSTREETS = {
    id: 'BACKSTREETS',
    name: '루멘포드 뒷골목',
    description: '도시와 도시 사이를 꿰매는 골목망. 젖은 콘크리트, 청록 네온, 증기가 교차하며 빠르게 이동하기 좋지만 매복도 잦다.',
    entryFieldId: 'alley-gate',
    prev: 'LUMENFORD',
    next: 'LIBRARY',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'noir-transit' },
    bg: {
        path: '/assets/bg/maps/backstreets/main.webp',
        position: 'center 65%',
        overlay: 'grain',
        grade: 'cool',
        description: '좁은 뒷골목. 파이프에서 뿜어 나오는 흰 증기가 천천히 흘러가고, 낡은 청록 네온 간판이 불규칙하게 깜빡인다. ' +
            '빗방울이 드문드문 떨어져 젖은 아스팔트에 타원형 반사를 만든다. 세탁줄과 전선이 프레임을 가로지른다.',
        gifRecommended: true,
        llmPrompt: 'Narrow worn‑teal cyberpunk back alley; slow steam from wall pipes; irregular teal neon flicker; sparse raindrops on wet asphalt; laundry lines and cables crossing; subtle loop.',
    },
    music: {
        mood: 'noir ticks + alley ambience',
        tracks: ['/assets/audio/maps/backstreets/noir.ogg'],
        loop: true,
        volume: 0.65,
        description: '미세한 메트로놈틱한 틱(우드/플라스틱), 낮은 패드, 물 떨어지는 잔향과 배기팬 저역 소음. ' +
            '템포는 느리고, 공간감은 좁은 골목 리버브를 적용.',
        llmPrompt: 'Minimal noir percussive ticks (wood/plastic), low pad, dripping water tails and low fan hum; slow tempo; narrow alley reverb; restrained mix.',
    },
    fields: [
        {
            id: 'alley-gate',
            name: '골목 입구(Entry)',
            kind: 'entry',
            description: '큰 도로에서 꺾여 들어오는 입구. 보안 카메라와 낡은 표지판.',
            neighbors: ['market-passage', 'checkpoint'],
            bg: {
                path: '/assets/bg/maps/backstreets/alley_gate.webp',
                position: 'center 70%',
                overlay: 'grain',
                grade: 'cool',
                description: '골목 표지판의 흐릿한 페인트, 고드름처럼 맺힌 물방울. 카메라 적외선 LED 링이 아주 약하게 빛난다.',
                gifRecommended: true,
                llmPrompt: 'Alley mouth with faded signage, hanging droplets like tiny icicles; faint IR LED ring glow on a security cam; subtle loop.',
            },
        },
        {
            id: 'market-passage',
            name: '시장 통로',
            kind: 'market',
            description: '상점 뒤편 통로. 목재 팔레트와 포장 상자 더미, 빠르게 지나가는 그림자.',
            neighbors: ['alley-gate', 'rooftops'],
            bg: {
                path: '/assets/bg/maps/backstreets/market_passage.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '젖은 시멘트 바닥에 팔레트의 거친 나뭇결, 상자 라벨의 바랜 잉크. 간헐적 발소리 그림자가 벽면을 스친다.',
                gifRecommended: true,
                llmPrompt: 'Back‑market passage with wet concrete, rough wooden pallets, faded ink labels; occasional shadow of footsteps sliding across the wall; seamless loop.',
            },
        },
        {
            id: 'checkpoint',
            name: '임시 검문소',
            kind: 'infrastructure',
            description: '메쉬 펜스와 이동식 배리어. 출입 기록표가 비에 젖어 들러붙어 있다.',
            neighbors: ['alley-gate'],
            bg: {
                path: '/assets/bg/maps/backstreets/checkpoint.webp',
                position: 'center',
                overlay: 'grain',
                grade: 'cool',
                description: '메쉬 펜스에 물방울이 맺혀 작게 반짝이고, 이동식 배리어의 반사띠가 젖은 바닥에서 늘어진다.',
                llmPrompt: 'Mesh fence with beads of water, portable barrier with retroreflective tape elongated on wet ground; cool tone; high texture detail.',
            },
        },
        {
            id: 'rooftops',
            name: '지붕길',
            kind: 'district',
            description: '비상 사다리를 타고 오르는 지붕길. 전선과 환기구, 낮게 흐르는 구름.',
            neighbors: ['market-passage'],
            bg: {
                path: '/assets/bg/maps/backstreets/rooftops.webp',
                position: 'center 45%',
                overlay: 'fog',
                grade: 'cool',
                description: '지붕 위 전선 다발과 회색 환기구. 멀리 바람에 밀린 구름층이 낮게 흐른다. 드문 번개가 먼 곳에서 반짝.',
                gifRecommended: true,
                llmPrompt: 'Rooftop with cable bundles and gray vents; low clouds drifting; occasional distant lightning glint; subtle parallax fog; loopable.',
            },
        },
    ],
};
const MAP_LIBRARY = {
    id: 'LIBRARY',
    name: '유적도서관',
    description: '봉인된 지하 열람실과 의식실이 연결된 잔해 도서관. 지식은 힘이지만 대가가 따른다.',
    entryFieldId: 'atrium',
    prev: 'BACKSTREETS',
    next: 'CAUSEWAY',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'mystic-danger' },
    bg: {
        path: '/assets/bg/maps/library/atrium.webp',
        position: 'center 55%',
        focalPoint: 'broken-oculus',
        parallax: 0.08,
        overlay: 'fog',
        grade: 'cool',
        description: '붕괴된 원형 천창(오쿨러스) 아래로 하얀 먼지가 빛기둥 속에 부유. ' +
            '바닥은 금이 간 대리석과 파편, 중간 톤의 청록 잔광이 룬 장식에 얕게 번짐. 공기 습한 느낌.',
        llmPrompt: 'Collapsed oculus with volumetric light shafts full of dust motes; cracked marble floor with fragments; faint teal afterglow on runes; moist cool air; fog overlay.',
    },
    music: {
        mood: 'choral shards + sub bass',
        tracks: [
            '/assets/audio/maps/library/echoes.ogg',
            '/assets/audio/maps/library/echoes.mp3',
        ],
        loop: true,
        volume: 0.65,
        cuePoints: [{ name: 'loop', time: 12.0 }],
        description: '파편화된 합창(미세하게 디튜닝), 낮은 서브 베이스가 서서히 파도처럼 부풀었다 가라앉음. ' +
            '금속성 종소리의 롱테일 리버브를 극히 낮은 볼륨으로 배경에 배치.',
        llmPrompt: 'Fragmented choir with slight detuning; slow swelling sub-bass; very low metallic chime tails; eerie but restrained; long reverb.',
    },
    fields: [
        {
            id: 'atrium',
            name: '아트리움(Entry)',
            kind: 'entry',
            description: '귤빛 유리 조각과 부러진 기둥이 난무하는 중앙 홀.',
            neighbors: ['stacks', 'scriptorium'],
            bg: {
                path: '/assets/bg/maps/library/atrium_close.webp',
                position: 'center',
                overlay: 'fog',
                grade: 'cool',
                description: '원형 난간과 중앙 제단 클로즈업. 제단 표면에 오래된 긁힘과 그을음, 옆 계단의 미세한 먼지층. ' +
                    '광선이 천천히 흔들리는 듯한 연출(루프 가능).',
                gifRecommended: true,
                llmPrompt: 'Close on circular balustrade and central dais; aged scratches and soot; thin dust layer on steps; gentle swaying volumetric light; seamless loop.',
            },
        },
        {
            id: 'stacks',
            name: '서가',
            kind: 'interior',
            description: '봉인 라벨이 붙은 서가. 사서 드론의 잔해가 보인다.',
            neighbors: ['atrium', 'vault'],
            bg: {
                path: '/assets/bg/maps/library/stacks.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '높은 서가가 만드는 협곡 같은 복도, 책등에 달라붙은 오래된 표찰. 먼지는 아주 미세하게 부유. ' +
                    '카메라는 눈높이, 원근을 강조하는 좁은 시야.',
                llmPrompt: 'Narrow canyon-like aisle between tall stacks; aged labels on book spines; minimal dust drift; eye-level camera; compressed perspective.',
            },
        },
        {
            id: 'scriptorium',
            name: '필사실',
            kind: 'interior',
            description: '의식 도면과 공허문자 낙서가 겹쳐진 작업대들.',
            neighbors: ['atrium'],
            bg: {
                path: '/assets/bg/maps/library/scriptorium.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '묵은 잉크 번짐과 촛농자국이 겹친 작업대. 유리 파편 위에 점状 반사가 어지럽게 찍힌다. ' +
                    '푸른 잔광이 금속 펜촉을 스치듯 반짝.',
                llmPrompt: 'Scriptorium desks stained with old ink and wax; scattered glass shards with point highlights; faint teal glint on metal nibs.',
            },
        },
        {
            id: 'vault',
            name: '의식 보관실',
            kind: 'vault',
            description: '차갑게 진동하는 봉인 룬. 접근에는 허가와 대가가 필요하다.',
            neighbors: ['stacks'],
            bg: {
                path: '/assets/bg/maps/library/vault.webp',
                position: 'center 45%',
                overlay: 'fog',
                grade: 'cool',
                description: '두꺼운 금속 금고문, 깊게 새겨진 룬 홈에서 강한 청록 발광이 새어 나온다. ' +
                    '주변 공기에는 아주 얇은 김이 올라오듯 미세한 빛 먼지가 흐른다.',
                gifRecommended: true,
                llmPrompt: 'Massive metal vault door with deeply engraved runes emitting strong teal light; thin shimmering dust like heat haze; loopable subtle pulse.',
            },
        },
    ],
};
const MAP_CAUSEWAY = {
    id: 'CAUSEWAY',
    name: '폭풍 경계 가도',
    description: '도시와 도시 사이의 외곽 순환로. 유리먼지와 잔잔한 낙진이 바람을 타고 스치며, 멀리 폭풍벽이 번개로 깜빡인다.',
    entryFieldId: 'outer-ring',
    prev: 'LIBRARY',
    next: 'SEWERS',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'windswept-peril' },
    bg: {
        path: '/assets/bg/maps/causeway/main.webp',
        position: 'center 55%',
        overlay: 'fog',
        grade: 'cool',
        description: '넓은 외곽 가도, 바닥에는 바랜 차선과 균열. 낮게 깔린 먼지층이 바람에 쓸려가며, ' +
            '수평선 너머 폭풍벽에서 희미한 번개가 주기적으로 번쩍인다.',
        gifRecommended: true,
        llmPrompt: 'Wide outer causeway with faded lane markings and cracks; low dust layer swept by wind; distant storm wall with periodic lightning; loopable wind motion.',
    },
    music: {
        mood: 'wind wall + distant thunder',
        tracks: ['/assets/audio/maps/causeway/wind_wall.ogg'],
        loop: true,
        volume: 0.6,
        description: '넓은 바람 소리와 먼 폭풍의 저주파 우르릉. 때때로 얇은 금속판 공명음이 짧게 섞인다. 공간감은 매우 넓음.',
        llmPrompt: 'Broad wind wall ambience with low distant thunder; occasional thin metal resonance; very wide spatial field; restrained dynamics.',
    },
    fields: [
        {
            id: 'outer-ring',
            name: '외곽 링(Entry)',
            kind: 'entry',
            description: '순환로 진입 구간. 표지판과 바리케이드 잔해.',
            neighbors: ['storm-bridge', 'watchpost'],
            bg: {
                path: '/assets/bg/maps/causeway/outer_ring.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '휘어진 표지판, 찢긴 배너 천 조각이 바람에 팔랑. 고정 볼트가 녹슬어 텍스처가 선명하다.',
                gifRecommended: true,
                llmPrompt: 'Bent signposts and torn banner strips flapping in the wind; rusty bolts with sharp texture; loopable flutter.',
            },
        },
        {
            id: 'storm-bridge',
            name: '폭풍교',
            kind: 'infrastructure',
            description: '낙차를 넘어가는 다리. 유리먼지가 바람에 반짝이며 지나간다.',
            neighbors: ['outer-ring', 'watchpost'],
            bg: {
                path: '/assets/bg/maps/causeway/storm_bridge.webp',
                position: 'center 55%',
                overlay: 'fog',
                grade: 'cool',
                description: '다리 상판 위로 미세한 유리먼지와 모래가 줄무늬로 쓸려간다. 손잡이 금속 표면에 작은 점상 반짝임.',
                gifRecommended: true,
                llmPrompt: 'Bridge deck with fine glass dust swept into striations; tiny point glints along metal handrails; loopable wind/dust motion.',
            },
        },
        {
            id: 'watchpost',
            name: '감시초소',
            kind: 'junction',
            description: '폐쇄된 초소. 도로 위 카메라와 비상 조명만 살아 있다.',
            neighbors: ['outer-ring', 'storm-bridge'],
            bg: {
                path: '/assets/bg/maps/causeway/watchpost.webp',
                position: 'center',
                overlay: 'grain',
                grade: 'cool',
                description: '작은 박스형 초소 내부에 잔광. 외부 비상등이 간헐적으로 점멸하며 주변 바닥에 장방형 빛 패턴을 만든다.',
                gifRecommended: true,
                llmPrompt: 'Boxy roadside watchpost with faint interior afterglow; exterior emergency light blinking intermittently, casting rectangular light patterns; loopable.',
            },
        },
    ],
};
const MAP_SEWERS = {
    id: 'SEWERS',
    name: '공허 수로',
    description: '도시 아래 흐르는 검은 물길. 소음은 멀리 퍼지고 빛은 큰 대가를 부른다.',
    entryFieldId: 'outfall',
    prev: 'CAUSEWAY',
    next: null,
    theme: { tag: 'dark-cyber-worn-teal', mood: 'perilous' },
    bg: {
        path: '/assets/bg/maps/sewers/outfall.webp',
        position: 'center bottom',
        focalPoint: 'spillway',
        parallax: 0.06,
        overlay: 'fog',
        grade: 'cool',
        description: '벽돌 아치형 터널 말단에서 낙차를 두고 물이 분출되어 얇은 수막을 만든다. ' +
            '벽면엔 물때와 산화 얼룩, 바닥엔 격자 배수로가 반사로 번들거린다. 공기는 탁하고 차갑다.',
        gifRecommended: true,
        llmPrompt: 'Brick arch tunnel outfall with thin waterfall sheet; oxidized stains; wet grates reflecting light; cold, murky air; loopable water motion.',
    },
    music: {
        mood: 'low drones + water',
        tracks: [
            '/assets/audio/maps/sewers/drone.ogg',
            '/assets/audio/maps/sewers/drip.ogg',
        ],
        loop: true,
        volume: 0.6,
        description: '저주파 드론과 불규칙 물방울/수막 소리. 드론은 일정하지 않게 미세한 피치 변화를 가지며, 공간감은 터널 잔향을 강조.',
        llmPrompt: 'Low-frequency drone with irregular dripping and thin waterfall noise; subtle pitch drift; strong tunnel reverb; cold and oppressive.',
    },
    fields: [
        {
            id: 'outfall',
            name: '방류구(Entry)',
            kind: 'entry',
            description: '커다란 방류구와 수막. 미끄러운 철제 난간.',
            neighbors: ['channel'],
            bg: {
                path: '/assets/bg/maps/sewers/outfall_close.webp',
                position: 'center bottom',
                overlay: 'fog',
                grade: 'cool',
                description: '수막 비말의 미세 입자, 녹과 칠이 벗겨진 난간 표면 거칠기. 물길에 흔들리는 조명 반사. ' +
                    '저속 루프에 적합한 잔잔한 흐름.',
                gifRecommended: true,
                llmPrompt: 'Close shot of misting water sheet and chipped rusty railing texture; shimmering light on flow; gentle seamless loop.',
            },
        },
        {
            id: 'channel',
            name: '본류',
            kind: 'infrastructure',
            description: '중앙 수로. 수면 아래에서 금속성 공명이 들린다.',
            neighbors: ['outfall', 'junction'],
            bg: {
                path: '/assets/bg/maps/sewers/channel.webp',
                position: 'center 65%',
                overlay: 'grain',
                grade: 'cool',
                description: '직선 본류가 멀리 사라지며 양측 벽엔 희미한 조명 라인이 연속. 수면엔 느린 흐름의 파형이 반복. 습기 찬 벽돌 질감 강조.',
                gifRecommended: true,
                llmPrompt: 'Long straight channel with faint repeating light lines along walls; slow waveform ripples; moist brick texture; loopable flow.',
            },
        },
        {
            id: 'junction',
            name: '분기점',
            kind: 'junction',
            description: '세 갈래로 갈라지는 연결부. 소용돌이가 생긴다.',
            neighbors: ['channel', 'breakwater'],
            bg: {
                path: '/assets/bg/maps/sewers/junction.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '세 갈래 분기, 바닥의 노란 안전 발판과 방향 표식. 물이 합쳐지는 와류가 중앙에 작게 생기며 리듬감 있게 반복.',
                gifRecommended: true,
                llmPrompt: 'Three-way junction with yellow safety plates and directional markings; small central eddy where flows meet; rhythmic repeating motion.',
            },
        },
        {
            id: 'breakwater',
            name: '파제벽',
            kind: 'ruin',
            description: '붕괴된 벽체와 떠내려온 잔해. 공허 흔적체가 남아 있다.',
            neighbors: ['junction'],
            bg: {
                path: '/assets/bg/maps/sewers/breakwater.webp',
                position: 'center 60%',
                overlay: 'fog',
                grade: 'cool',
                description: '균열난 벽체와 찌그러진 난간, 떠내려와 걸린 잔해 뭉치. 물 표면엔 느린 기포와 소용돌이가 드문 간격으로 일어난다.',
                gifRecommended: true,
                llmPrompt: 'Cracked wall and bent railings with tangled debris; slow bubbles and occasional small whirlpools; subtle loop.',
            },
        },
    ],
};
const MAP_HIGHWAY = {
    id: 'HIGHWAY',
    name: '붕괴 고속도로',
    description: '도시권을 벗어난 외곽 고속도로. 교각 일부가 무너져 차선이 끊기고, 바람에 유리먼지가 실려 반짝인다.',
    entryFieldId: 'onramp',
    prev: 'SEWERS',
    next: 'SUBWAY_LINE',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'exposed-travel' },
    bg: {
        path: '/assets/bg/maps/highway/main.webp',
        position: 'center 60%',
        overlay: 'fog',
        grade: 'cool',
        description: '해질녘, 고속도로 상판에 균열과 잡초가 드문드문 자랐다. 붕괴된 교각 잔해가 아래 골짜기로 떨어져 있고, ' +
            '차선 페인트는 바래어 끊긴 점선이 된다. 도로 표면에는 미세한 유리먼지가 얇게 깔려 바람이 지날 때 점状 반짝임을 만든다. ' +
            '프레이밍: 3분할 구성, 좌측 하단에 끊긴 가드레일, 우측 상단에 붕괴 흔적, 원근선은 중앙 소실점.',
        gifRecommended: true,
        llmPrompt: 'Dusk collapsed expressway; cracked deck with sparse weeds; broken piers in ravine; faded lane paint; thin glass dust glittering in wind; thirds composition with vanishing point center; loopable wind shimmer.',
    },
    music: {
        mood: 'wind shear + distant traffic ghosts',
        tracks: ['/assets/audio/maps/highway/wind_shear.ogg'],
        loop: true,
        volume: 0.6,
        description: '넓은 바람 소리 위에 희미한 고속 주행 잔상(흐릿한 도플러), 금속 가드레일이 미세하게 떨며 내는 공명. ' +
            '템포 없음, 낮은 다이내믹, 냉색 잔향.',
        llmPrompt: 'Wide wind ambience with faint ghostly traffic dopplers; subtle metal guardrail resonance; atonal; low dynamics; cool-tail reverb.',
    },
    fields: [
        {
            id: 'onramp',
            name: '진입 램프(Entry)',
            kind: 'entry',
            description: '폐쇄 배리어를 치우고 진입하는 램프 구간. 표지판과 잡초.',
            neighbors: ['overpass', 'wreck-lanes'],
            bg: {
                path: '/assets/bg/maps/highway/onramp.webp',
                position: 'center 65%',
                overlay: 'grain',
                grade: 'cool',
                description: '진입 차선의 화살표가 반쯤 지워져 있고 잡초가 표면을 뚫고 나온다. 폐쇄 배리어의 반사띠가 바람에 미세하게 흔들린다.',
                gifRecommended: true,
                llmPrompt: 'Highway on-ramp with half-erased arrows and weeds breaking through; barrier retroreflective tape subtly fluttering; loopable.',
            },
        },
        {
            id: 'overpass',
            name: '고가 교차로',
            kind: 'infrastructure',
            description: '서로 다른 층의 도로가 겹치는 구간. 교각 그림자와 균열.',
            neighbors: ['onramp', 'wreck-lanes'],
            bg: {
                path: '/assets/bg/maps/highway/overpass.webp',
                position: 'center 55%',
                overlay: 'fog',
                grade: 'cool',
                description: '교각이 겹쳐 만든 깊은 그림자. 균열 사이로 식생이 자라며, 상판 가장자리 철근이 드러나 녹빛 얼룩이 번진다.',
                llmPrompt: 'Layered overpass shadows; cracks with sprouting plants; exposed rebar with green rust stains; cool fog overlay.',
            },
        },
        {
            id: 'wreck-lanes',
            name: '차량 잔해 구간',
            kind: 'ruin',
            description: '뒤엉킨 차량 잔해가 길을 막는다. 일부는 반쯤 매몰.',
            neighbors: ['onramp', 'overpass'],
            bg: {
                path: '/assets/bg/maps/highway/wreck_lanes.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '폐차 더미와 흩어진 유리 파편, 눌린 차체의 주름과 벗겨진 도색. 바람에 걸린 범퍼 천 조각이 간헐적으로 흔들린다.',
                gifRecommended: true,
                llmPrompt: 'Tangled car wrecks with scattered glass shards; crushed sheet metal creases and flaked paint; occasional fluttering fabric; loopable subtle motion.',
            },
        },
    ],
};
const MAP_SUBWAY = {
    id: 'SUBWAY_LINE',
    name: '폐 지하철 선로',
    description: '철문이 열린 서비스 입구를 통해 들어가는 폐 선로. 물웅덩이와 깜빡이는 비상등, 오래된 광고판이 남아 있다.',
    entryFieldId: 'service-entrance',
    prev: 'HIGHWAY',
    next: 'REFINERY_BELT',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'echoing-underground' },
    bg: {
        path: '/assets/bg/maps/subway/main.webp',
        position: 'center 55%',
        overlay: 'fog',
        grade: 'cool',
        description: '플랫폼 기둥과 선로가 평행으로 사라진다. 바닥에는 물웅덩이가 점점이 찍혀 조명 반사를 일그러뜨리고, ' +
            '비상등은 불규칙한 간격으로 깜빡인다. 오래된 광고판은 벗겨진 종이와 녹 얼룩으로 질감이 거칠다.',
        gifRecommended: true,
        llmPrompt: 'Abandoned subway with parallel tracks; puddles causing wavy reflections; intermittent emergency light flicker; torn paper ads with rust stains; loopable flicker and ripple.',
    },
    music: {
        mood: 'sub-bass rumbles + fluorescent buzz',
        tracks: ['/assets/audio/maps/subway/rumble.ogg'],
        loop: true,
        volume: 0.55,
        description: '낮은 럼블과 형광등 버즈가 교차. 멀리서 들리는 금속 굴림 잔향(희귀). 공간감은 터널 중심에 집중.',
        llmPrompt: 'Low rumbles with fluorescent light buzz; rare distant metal roll echoes; centered tunnel reverb; sparse textures.',
    },
    fields: [
        {
            id: 'service-entrance',
            name: '서비스 입구(Entry)',
            kind: 'entry',
            description: '철문과 좁은 계단, 경고 표지판. 습기와 곰팡이 냄새.',
            neighbors: ['platform', 'tunnel'],
            bg: {
                path: '/assets/bg/maps/subway/service_entrance.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '녹슨 철문과 경사 계단. 계단 모서리에 물방울이 맺혀 반짝이며, 경고 표지판의 글자는 반쯤 벗겨져 있다.',
                gifRecommended: true,
                llmPrompt: 'Rusty steel door and inclined stair; droplets glinting on step edges; peeling warning signage; loopable micro-drips.',
            },
        },
        {
            id: 'platform',
            name: '플랫폼',
            kind: 'infrastructure',
            description: '열차는 없다. 광고판과 벤치, 행선 LED 잔광.',
            neighbors: ['service-entrance', 'tunnel'],
            bg: {
                path: '/assets/bg/maps/subway/platform.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '플랫폼 벽면의 라이트 박스가 간헐적으로 남은 전류로 깜빡이며, 벤치 금속 다리엔 찌든 자국이 번져 있다.',
                gifRecommended: true,
                llmPrompt: 'Platform lightboxes faintly flicker from residual current; stained metal bench legs; loopable flicker.',
            },
        },
        {
            id: 'tunnel',
            name: '터널',
            kind: 'infrastructure',
            description: '균일한 선로와 케이블 볼트. 소리의 꼬리만 남는다.',
            neighbors: ['service-entrance', 'platform'],
            bg: {
                path: '/assets/bg/maps/subway/tunnel.webp',
                position: 'center 55%',
                overlay: 'fog',
                grade: 'cool',
                description: '벽면 케이블 고정 볼트가 반복 패턴을 이루며, 원근감이 강하게 느껴진다. 먼지 입자가 헤드램프 없는 어둠 속에서 천천히 흐른다.',
                llmPrompt: 'Tunnel with repeating cable bolts; strong perspective; slow floating dust in headlamp-less darkness; cool fog overlay.',
            },
        },
    ],
};
const MAP_REFINERY = {
    id: 'REFINERY_BELT',
    name: '정유 벨트',
    description: '파이프라인과 탱크가 늘어선 공업 지대. 플레어 스택은 꺼졌고, 오일 자국만 바닥에 남아 있다.',
    entryFieldId: 'pipeway',
    prev: 'SUBWAY_LINE',
    next: 'CLOSED_AIRFIELD',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'industrial-desolate' },
    bg: {
        path: '/assets/bg/maps/refinery/main.webp',
        position: 'center 55%',
        overlay: 'grain',
        grade: 'cool',
        description: '지면에 고여 번들거리는 오일 자국과 얽힌 파이프 숲. 밸브 휠의 페인트가 벗겨져 금속 바탕이 드러나며, ' +
            '플레어 스택은 냉각되어 잔열만 공기 왜곡으로 떠오른다.',
        gifRecommended: true,
        llmPrompt: 'Pipeline forest with glossy oil puddles; peeling valve wheel paint exposing metal; cooled flare stacks with subtle heat haze; loopable shimmer.',
    },
    music: {
        mood: 'metal groan + oil drip',
        tracks: ['/assets/audio/maps/refinery/metal_groan.ogg'],
        loop: true,
        volume: 0.6,
        description: '느린 금속 하중음과 드문 오일 방울 소리. 넓은 리버브는 억제, 중저역 질감 강조.',
        llmPrompt: 'Slow metal load groans with sparse oil drip; restrained reverb; mid-low texture emphasis.',
    },
    fields: [
        {
            id: 'pipeway',
            name: '파이프 웨이(Entry)',
            kind: 'entry',
            description: '파이프 트러스 아래의 통로. 격자 그림자.',
            neighbors: ['cracking-yard', 'flare-stack'],
            bg: {
                path: '/assets/bg/maps/refinery/pipeway.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '격자 트러스 그림자가 바닥에 격자로 드리워지고, 바람에 눌리는 비닐 시트가 파이프에 걸려 떨린다.',
                gifRecommended: true,
                llmPrompt: 'Pipe truss casting grid shadows; plastic sheet caught and fluttering; loopable flutter.',
            },
        },
        {
            id: 'cracking-yard',
            name: '분해 공정 야드',
            kind: 'infrastructure',
            description: '정지된 장치와 안전 페인트. 표식은 자주색/노랑 대비.',
            neighbors: ['pipeway', 'flare-stack'],
            bg: {
                path: '/assets/bg/maps/refinery/cracking_yard.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '자주색 위험 표식과 노란 안전 라인. 장치 표면에는 스케일이 끼어 거칠고, 볼트 주변엔 기름때 무늬.',
                llmPrompt: 'Cracking units with purple hazard signs and yellow safety lines; scaled rough surfaces; oil grime halos around bolts.',
            },
        },
        {
            id: 'flare-stack',
            name: '플레어 스택',
            kind: 'infrastructure',
            description: '꺼진 스택. 잔열의 공기 떨림만 남아 있다.',
            neighbors: ['pipeway', 'cracking-yard'],
            bg: {
                path: '/assets/bg/maps/refinery/flare_stack.webp',
                position: 'center 50%',
                overlay: 'fog',
                grade: 'cool',
                description: '수직 스택과 계단. 금속 난간에 응결수, 상단 배출구 주변 공기 굴절이 미세하게 일렁인다.',
                gifRecommended: true,
                llmPrompt: 'Vertical flare stack and stair; condensation on rails; subtle refractive shimmer near the outlet; loopable.',
            },
        },
    ],
};
const MAP_AIRFIELD = {
    id: 'CLOSED_AIRFIELD',
    name: '폐 공항 활주로',
    description: '폐쇄된 활주로와 비행격납고. 바람에 모래와 유리먼지가 지나가고, 유도등은 일부만 살아 깜빡인다.',
    entryFieldId: 'runway-entry',
    prev: 'REFINERY_BELT',
    next: 'ASHENPORT',
    theme: { tag: 'dark-cyber-worn-teal', mood: 'open-winds' },
    bg: {
        path: '/assets/bg/maps/airfield/main.webp',
        position: 'center 55%',
        overlay: 'fog',
        grade: 'cool',
        description: '긴 활주로 중앙선이 소실점으로 뻗는다. 표면의 균열 사이로 모래가 쌓이고, 유도등 몇 개는 주기적으로 희미하게 점등된다. ' +
            '멀리 격납고 실루엣과 관제탑이 낮게 솟아 있다.',
        gifRecommended: true,
        llmPrompt: 'Closed runway with long centerline to vanishing point; sand collected in cracks; few taxi lights faintly blinking; distant hangars and tower silhouettes; loopable wind/sand motion.',
    },
    music: {
        mood: 'windscape + beacon ticks',
        tracks: ['/assets/audio/maps/airfield/windscape.ogg'],
        loop: true,
        volume: 0.6,
        description: '넓은 바람 위에 희미한 비콘 틱이 간헐적으로 섞이는 구성. 저역은 억제하고 고역 바람 결을 살린다.',
        llmPrompt: 'Wide wind with occasional beacon ticks; low end restrained; emphasize high-frequency wind textures; sparse.',
    },
    fields: [
        {
            id: 'runway-entry',
            name: '활주로 입구(Entry)',
            kind: 'entry',
            description: '활주로 표식과 배리어. 바람이 강하다.',
            neighbors: ['hangars', 'control-tower'],
            bg: {
                path: '/assets/bg/maps/airfield/runway_entry.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '활주로 번호가 크게 적힌 표식. 일부 페인트가 바래고 갈라졌다. 바람에모래가 얇은 커튼처럼 스친다.',
                gifRecommended: true,
                llmPrompt: 'Runway threshold numbers faded and cracked; thin curtains of sand blown across; loopable.',
            },
        },
        {
            id: 'hangars',
            name: '격납고',
            kind: 'infrastructure',
            description: '슬라이딩 도어가 반쯤 열린 격납고. 내부는 어둡다.',
            neighbors: ['runway-entry', 'control-tower'],
            bg: {
                path: '/assets/bg/maps/airfield/hangars.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '거대한 슬라이딩 도어 틈에서 바람이 일며 내부 먼지가 비스듬히 움직인다. 금속 골조가 반복 패턴을 만든다.',
                gifRecommended: true,
                llmPrompt: 'Hangar sliding door half open; oblique dust drift inside; repeating steel frame pattern; loopable.',
            },
        },
        {
            id: 'control-tower',
            name: '관제탑',
            kind: 'infrastructure',
            description: '사다리와 유리 박스. 내부 패널 일부가 살아 있다.',
            neighbors: ['runway-entry', 'hangars'],
            bg: {
                path: '/assets/bg/maps/airfield/control_tower.webp',
                position: 'center 50%',
                overlay: 'fog',
                grade: 'cool',
                description: '유리 박스형 탑 상부에 계단과 발판. 내부 패널 LED 일부가 박동하듯 아주 느리게 밝아진다.',
                gifRecommended: true,
                llmPrompt: 'Glass box tower top with stairs/platform; interior panel LEDs pulsing very slowly; loopable subtle pulse.',
            },
        },
    ],
};
const MAP_ASHENPORT = {
    id: 'ASHENPORT',
    name: '재빛 항구도시',
    description: '재와 유리 슬래그가 쌓인 해안 도시. 방파제와 건조 도크, 낮고 무거운 구름 하늘 아래 잿빛 바다가 펼쳐진다.',
    entryFieldId: 'gate',
    prev: 'CLOSED_AIRFIELD',
    next: null,
    theme: { tag: 'dark-cyber-worn-teal', mood: 'harbor-gloom' },
    bg: {
        path: '/assets/bg/maps/ashenport/main.webp',
        position: 'center 60%',
        overlay: 'fog',
        grade: 'cool',
        description: '방파제 끝에 녹슨 표식과 신호등, 건조 도크의 크레인이 조용히 서 있다. 바다는 잔물결이 느리게 번지고, 하늘은 낮게 드리운 연회색 층운.',
        gifRecommended: true,
        llmPrompt: 'Harbor breakwater with rusty markers and signal lights; dry-dock cranes; slow ripples on gray sea; low stratus clouds; loopable water motion.',
    },
    music: {
        mood: 'sea mist + low horns',
        tracks: ['/assets/audio/maps/ashenport/sea_mist.ogg'],
        loop: true,
        volume: 0.6,
        description: '해무 앰비언스와 낮은 혼 경적이 드물게 섞임. 금속 케이블 삭는 소리가 아주 낮은 레벨로 배경에 깔린다.',
        llmPrompt: 'Sea mist ambience with rare low foghorns; faint metal cable creak; restrained mix.',
    },
    fields: [
        {
            id: 'gate',
            name: '항구 문(Entry)',
            kind: 'entry',
            description: '항구 도시의 관문. 통행 펜스와 경비 박스.',
            neighbors: ['dry-docks', 'civic-hall'],
            bg: {
                path: '/assets/bg/maps/ashenport/gate.webp',
                position: 'center 60%',
                overlay: 'grain',
                grade: 'cool',
                description: '메쉬 펜스 뒤로 컨테이너 실루엣이 겹겹이 쌓이고, 경비 박스의 작은 창에 실내 조명이 은은히 번진다.',
                llmPrompt: 'Harbor gate with mesh fence, stacked container silhouettes; guard booth window with faint interior light; cool grain.',
            },
        },
        {
            id: 'dry-docks',
            name: '건조 도크',
            kind: 'infrastructure',
            description: '선체 지지대와 크레인. 바닥은 녹과 기름 얼룩.',
            neighbors: ['gate', 'civic-hall'],
            bg: {
                path: '/assets/bg/maps/ashenport/dry_docks.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '선체 지지대가 리듬감 있게 반복되며, 크레인의 케이블이 바람에 느리게 떨린다. 바닥의 오일 웰트가 점状 반짝임.',
                gifRecommended: true,
                llmPrompt: 'Dry-dock with repeating hull supports; crane cables slowly vibrating; oil speckles glinting; loopable.',
            },
        },
        {
            id: 'civic-hall',
            name: '시민 회관',
            kind: 'district',
            description: '낮고 넓은 로비 공간. 공지판과 쉼터 벤치.',
            neighbors: ['gate', 'dry-docks'],
            bg: {
                path: '/assets/bg/maps/ashenport/civic_hall.webp',
                position: 'center 55%',
                overlay: 'grain',
                grade: 'cool',
                description: '광택 없는 석재 바닥과 긴 그림자. 공지판에는 낡은 종이가 어긋나게 겹쳐 붙어 있고, 벤치의 금속 팔걸이는 차갑게 빛난다.',
                llmPrompt: 'Matte stone floor with long shadows; layered old paper notices; cold sheen on metal bench armrests; subdued cool palette.',
            },
        },
    ],
};
export const WORLD_STATIC = {
    id: 'GREYFALL_CORE',
    name: 'Greyfall — Solas Basin',
    head: 'LUMENFORD',
    maps: [
        MAP_LUMENFORD,
        MAP_BACKSTREETS,
        MAP_LIBRARY,
        MAP_CAUSEWAY,
        MAP_SEWERS,
        MAP_HIGHWAY,
        MAP_SUBWAY,
        MAP_REFINERY,
        MAP_AIRFIELD,
        MAP_ASHENPORT,
    ],
};
